<?php //if($this->getOrder()->getPayment()->getMethod()=='fastcash_transferencia'): ?>
<ul>
    <li>
        <?php echo 'Ocorreu um erro ao enviar os dados.' ?>
    </li>
</ul>
<?php //endif; ?>
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
